### ISSUE TITLE
AkashJS QueryLeaseRequest and QueryLeaseResponse Provide Inaccurate Price Details

### ISSUE THREAD

**Issue by akash-mm** [ovrclk/akashjs#30] opened 2022-07-07 21:32 UTC
Got a report from an AkashJS user this afternoon that there appears to be an issue with QueryLeaseRequest and QueryLeaseResponse.

In the example response snippet below the price in UAKT is 1524000000000000000 which would be 1524000000000 AKT.   And this appears in all leases in response - very large amounts that obviously do not seem accurate.

    {
        "lease": {
            "leaseId": {
                "owner": "akash1lugc2003ns4s2v8fwlhxpj0m8qf5z73x4tfz6p",
                "dseq": "5895298",
                "gseq": 1,
                "oseq": 1,
                "provider": "akash1uz6fslqf28fdhjtqa503sy7rp37vpw0xfnhgk8"
            },
            "state": "active",
            "price": {
                "denom": "uakt",
                "amount": "1524000000000000000"
            },
            "createdAt": "5895316",
            "closedOn": "0"
        },
        "escrowPayment": {
            "accountId": {
                "scope": "deployment",
                "xid": "akash1lugc2003ns4s2v8fwlhxpj0m8qf5z73x4tfz6p/5895298"
            },
            "paymentId": "1/1/akash1uz6fslqf28fdhjtqa503sy7rp37vpw0xfnhgk8",
            "owner": "akash1uz6fslqf28fdhjtqa503sy7rp37vpw0xfnhgk8",
            "state": "open",
            "rate": {
                "denom": "uakt",
                "amount": "1524000000000000000"
            },
            "balance": {
                "denom": "uakt",
                "amount": "976000000000000000"
            },
            "withdrawn": {
                "denom": "uakt",
                "amount": "1126424"
            }
        }
    }

**Comment by akash-mm** [comment] 2022-07-07 21:34
https://akashnetwork.atlassian.net/browse/SUPPORT-195

**Comment by jtary** [comment] 2022-07-12 16:03
Been able to exclude any of the bespoke code in AkashJS from causing the issues. Seems the problem is due to a malfunctioning decoder inside of the code autogenerated by ts-proto (specifically the DecCoin decoder). Still working on figuring out a solution.

**Comment by chandadharap** [comment] 2022-07-13 23:56
Do you need help on this?

**Comment by jtary** [comment] 2022-07-15 01:46
Released as akashjs@0.1.1

**Closed by jtary** 2022-07-15 01:46 UTC
Labels: Support
